[workspace]
resolver = "3"
members = ["crates/myactuator-rmd", "crates/myactuator-rmd-can"]

[workspace.package]
version = "0.1.4"
edition = "2024"
license = "Apache-2.0"
authors = ["nop <noplab90@gmail.com>"]
repository = "https://github.com/MechanicalGirlDev/myactuator-rmd-driver"

[workspace.lints.rust]
unsafe_code = "deny"
missing_docs = "deny"
missing_debug_implementations = "warn"
unused_import_braces = "warn"
unused_qualifications = "warn"
unused_results = "warn"
variant_size_differences = "warn"

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
std_instead_of_core = "warn"
std_instead_of_alloc = "warn"
